apiVersion: v1
kind: Namespace
metadata:
  name: resharper-server
---
apiVersion: v1
kind: Service
metadata:
  name: resharper-svc
  labels:
    app: resharper
  namespace: resharper-server
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: resharper
    tier: operations
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resharper-pv-claim
  labels:
    app: resharper
  namespace: resharper-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resharper-fls
  labels:
    app: resharper
  namespace: resharper-server
spec:
  selector:
    matchLabels:
      app: resharper
      tier: operations
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resharper
        tier: operations
      namespace: resharper-server
    spec:
      containers:
      - image: resharper-fls:latest
        name: resharper-fls        
        ports:
        - containerPort: 8080
          name: resharper-port
        volumeMounts:
        - name: resharper-persistent-storage
          mountPath: /user/resharper
      volumes:
      - name: resharper-persistent-storage
        persistentVolumeClaim:
          claimName: resharper-pv-claim
      imagePullSecrets:
      - name: container-reg